---
title: "getlambdamu"
author: "Claire Jellison"
date: "12/14/2019"
output: pdf_document
---

```{r}
allbike <- read.csv("data/full_bikes_named.csv")
```

```{r}
library(dplyr)
library(tidyr)
```

```{r}
head(allbike)
```

```{r}
days <- 184
departures <- allbike %>% group_by(StartHub) %>% summarise(tripsleave = as.integer(n_distinct(RouteID))) %>% mutate(hub = StartHub)
arrivals <- allbike %>% group_by(EndHub) %>% summarise(tripsarrive = as.integer(n_distinct(RouteID))) %>% mutate(hub = EndHub)
lambdamu <- left_join(departures, arrivals, by= "hub")
lambdamu <- lambdamu %>% select(hub, tripsleave, tripsarrive)
lambdamu <- lambdamu %>% mutate(lambda = tripsarrive/days) %>% mutate(mu = tripsleave/days)   #lambda is arrival of bikes, mu is departure of bikes
```

```{r}
#lambdamuf <- lambdamu[!grepl('Pop Up',lambdamu$hub),] #get rid of pop up stations
#head(lambdamuf)
```

```{r}
#get them holding times 
lambdamu <- lambdamu %>% mutate(q = lambda + mu) %>% arrange(desc(mu))
head(lambdamu,20)
```

```{r}
allbikeq <- allbike %>%
  mutate(yesno = 1) %>%
  distinct %>%
  spread(EndHub, yesno, fill = 0)
allbikeq <- allbikeq %>% select(-X, -RouteID, -PaymentPlan, -StartLatitude, -StartLongitude, -StartDate, -StartTime, -EndLatitude, -EndLongitude, -EndDate, - EndTime, -TripType, -BikeID, -BikeName, -Distance_Miles, -Duration, -RentalAccessPath, -MultipleRental, -StartHub2, -EndHub2)

```


```{r}
sumtorate <- function(col) { 
  rate <- (sum(col))/184
  rate
  }
allbikeq <- allbikeq %>% group_by(StartHub) %>% summarise_all(funs(sumtorate))
allbikeq <- allbikeq %>% mutate(totalout = rowSums(.[2:176]))
allbikeqv <- allbikeq %>% select(StartHub, totalout) %>% arrange(desc(totalout))
head(allbikeqv)
```


